reearth/reearth-marketplace

- .eslintignore
- web/package.json
- web/src/App.tsx
- web/src/Test.tsx
- web/src/extension.ts
- web/src/main.tsx
- web/vite.config.ext.ts
Set up Vite config for extensions of Re:Earth
> chore(web): set up Vite config for extension

- server/internal/adapter/gql/generated.go
- server/internal/adapter/gql/gqlmodel/plugin.go
- server/internal/infrastrcture/mongo/plugin.go
- server/internal/usecase/interactor/plugin.go
- server/internal/usecase/interfaces/plugin.go
- server/internal/usecase/repo/plugin.go
- server/schema.graphql
I added liked field to the plugin
> feat(server): add liked field to the plugin

- server/gqlgen.yml
- server/internal/adapter/gql/generated.go
- server/internal/adapter/gql/gqlmodel/convert_plugin.go
- server/internal/adapter/gql/gqlmodel/convert_user.go
- server/internal/adapter/gql/gqlmodel/models_gen.go
- server/internal/adapter/gql/gqlmodel/plugin.go
- server/internal/adapter/gql/gqlmodel/user.go
- server/internal/adapter/gql/resolver_query.go
- server/internal/infrastrcture/mongo/plugin.go
- server/internal/usecase/interactor/plugin.go
- server/internal/usecase/interactor/user.go
- server/internal/usecase/interfaces/plugin.go
- server/internal/usecase/interfaces/user.go
- server/internal/usecase/repo/plugin.go
I added global object identifier support
> feat(server): support global object identifier

- server/internal/adapter/http/plugin.go
- server/internal/app/app.go
- server/internal/app/http.go
- server/internal/infrastrcture/gcs/file.go
- server/internal/infrastrcture/mongo/plugin.go
- server/internal/usecase/gateway/file.go
- server/internal/usecase/interactor/plugin.go
- server/internal/usecase/interfaces/plugin.go
- server/pkg/plugin/builder.go
- server/pkg/plugin/plugin.go
I added a plugin download endpoints
> feat(server): add plugin download endpoints

- server/internal/app/app.go
> fix(server): remove allow headers

- web/src/gql/provider.tsx
I removed HttpLink because multiple terminal links (HttpLink, UploadLink) are invalid.
> fix(web): remove HttpLink

- server/internal/adapter/context.go
> fix(server): fix ContextAuthInfo type

- server/internal/infrastrcture/mongo/mongodoc/plugin.go
- server/pkg/id/plugin.go
- server/pkg/plugin/builder.go
- server/pkg/plugin/plugin.go
- server/pkg/plugin/pluginpack/package.go
> fix(server): fix ParsePlugin bugs

- server/internal/infrastrcture/mongo/plugin.go
- server/internal/usecase/interactor/plugin.go
I added support for duplicate pluginIDs and versions
> fix(server): support for duplicate pluginIDs and versions

- server/internal/adapter/gql/resolver_mutation_plugin.go
> fix(server): wrap id.PluginIDFrom

- server/internal/infrastrcture/mongo/plugin.go
> feat: to case-insensitive search

- server/internal/adapter/gql/gqlmodel/convert_plugin.go
- server/internal/adapter/gql/gqlmodel/plugin.go
I changed to use id instead of ID.
> fix(server): use id instead of ID

- server/internal/infrastrcture/mongo/plugin.go
> fix(server): fix unlike plugin

- server/internal/infrastrcture/mongo/plugin.go
> fix(server): fix search liked

- server/internal/app/auth_client.go
- server/internal/infrastrcture/mongo/mongo_test.go
- server/internal/infrastrcture/mongo/user.go
- server/internal/infrastrcture/mongo/user_test.go
- server/internal/usecase/repo/user.go
- server/pkg/user/user.go
- server/pkg/user/user_test.go
I added to logic about the initial user name.
I wrote unit tests.
> feat(server): add initial user name

- web/src/components/molecules/PluginDetailPage/ModalContent.tsx
- web/src/components/molecules/SearchArea/index.tsx
> fix: workspace modal and theming text colors

- server/internal/app/app.go
- server/internal/app/auth_client.go
- server/internal/app/main.go
I added m2m authentication (`REEARTH_MARKETPLACE_MACHINEAUTHSUB`) to `/api/plugins`
> feat(server): add m2m authentication to /api/plugins

- server/internal/usecase/interactor/plugin.go
I changed to cannot update other's plugin.
> fix(server): to cannot update other's plugin

- server/internal/infrastrcture/mongo/organization.go
- server/internal/infrastrcture/mongo/plugin.go
- server/pkg/main.go
> chore(server): fix create indexes

- web/src/components/molecules/Common/Header.tsx
- web/src/components/molecules/PluginDetailPage/index.tsx
- web/src/config.ts
- web/src/vite-env.d.ts
> feat: add report plugin url to config and button

- web/src/components/molecules/PluginDetailPage/index.tsx
- web/src/components/molecules/PluginsList.tsx
- web/src/components/molecules/PluginsListCard/index.tsx
- web/src/components/organisms/Top/hooks.ts
- web/src/components/organisms/Top/index.tsx
- web/src/gql/graphql-client-api.tsx
- web/src/gql/queries/plugin.ts
- web/src/gql/queries/user.ts
> feat: hearts are red on the root page if personally liked

- server/internal/infrastrcture/mongo/plugin.go
- server/internal/usecase/interactor/plugin.go
- server/pkg/plugin/plugin.go
- server/pkg/plugin/pluginpack/package.go
> fix(server): updatedAt and publishedAt

- server/internal/infrastrcture/mongo/plugin.go
> fix(server): save plugin's active

- .vscode/settings.json
- server/internal/adapter/gql/resolver_query.go
- server/internal/infrastrcture/mongo/mongodoc/plugin.go
- server/internal/infrastrcture/mongo/plugin.go
- server/internal/infrastrcture/mongo/plugin_test.go
- server/internal/usecase/interactor/plugin.go
- server/internal/usecase/interfaces/plugin.go
- server/internal/usecase/repo/plugin.go
- server/pkg/plugin/builder.go
> fix(server): hide inactive plugins from nodes query

- server/internal/infrastrcture/mongo/plugin.go
- server/internal/infrastrcture/mongo/plugin_test.go
- server/pkg/id/plugin.go
> fix(server): to keep plugin status

- web/src/components/molecules/Common/Header/Header.tsx
- web/src/components/molecules/Common/PluginUpload/PackageArea.tsx
- web/src/components/molecules/Common/PluginUpload/index.tsx
- web/src/components/molecules/MyPluginsPage/MyPluginsTable.tsx
- web/src/components/organisms/Common/PluginUpload/hooks.ts
- web/src/components/organisms/Common/PluginUpload/index.tsx
> fix: update workflow when uploading different plugin

- web/src/components/organisms/Common/PluginUpload/index.tsx
> fix: published status not showing correctly after redirect

- web/src/components/atoms/Carousel/index.tsx
> fix: carousel styles in extension

- server/internal/infrastrcture/mongo/plugin.go
- server/internal/infrastrcture/mongo/plugin_test.go
- server/pkg/plugin/builder.go
I fixed decoding cursor method
> fix(server): fix pagination

- server/go.mod
- server/go.sum
- server/internal/adapter/gql/generated.go
- server/internal/adapter/gql/gqlmodel/me.go
- server/internal/adapter/gql/gqlmodel/models_gen.go
- server/internal/adapter/gql/gqlmodel/user.go
- server/internal/adapter/gql/resolver_query.go
- server/internal/infrastrcture/mongo/plugin.go
- server/internal/infrastrcture/mongo/plugin_test.go
- server/internal/usecase/interfaces/plugin.go
- server/schema.graphql
> feat(server): add offset

- web/src/components/molecules/MyPluginsPage/MyPluginsTable.tsx
- web/src/components/molecules/MyPluginsPage/index.tsx
- web/src/components/molecules/PluginsListCard/index.tsx
- web/src/components/molecules/SearchArea/index.tsx
- web/src/components/molecules/TopPage/TopPageContents.tsx
- web/src/components/molecules/TopPage/index.tsx
- web/src/components/molecules/UserPage/index.tsx
- web/src/components/organisms/MyPlugins/hooks.ts
- web/src/components/organisms/MyPlugins/index.tsx
- web/src/components/organisms/Top/hooks.ts
- web/src/components/organisms/Top/index.tsx
- web/src/components/organisms/User/hooks.ts
- web/src/components/organisms/User/index.tsx
- web/src/gql/graphql-client-api.tsx
- web/src/gql/graphql.schema.json
- web/src/gql/provider.tsx
- web/src/gql/queries/plugin.ts
- web/src/gql/queries/user.ts
> feat(web): add pagination

- web/src/i18n/translations/ja.yml
Change the words to keep the layout
> chore: Update ja.yml

- web/src/components/atoms/Pagination/index.tsx
- web/src/components/molecules/TopPage/TopPageContents.tsx
> fix(web): extension missing styles

- web/src/components/molecules/PluginDetailPage/index.tsx
> chore(web): clean up

- web/src/components/organisms/PluginDetail/hooks.ts
This is only a workaround, we should implement load by page or load by current selected workspace.
> fix(web): projects not fully loaded

- .github/workflows/web_build.yml
Fixed buildx to specify all tags since only one tag was specified.
> ci(web): fix tag specification for buildx

- .github/workflows/deploy_server_nightly.yml
- .github/workflows/deploy_web_nightly.yml
> ci: update secrets for WI federation

- .github/workflows/ci.yml
> ci: use step-security for changed-files action
